import { ink, parchment, brass } from "./theme.js";

export const S = {
  shell: { minHeight: "100vh", background: `radial-gradient(1200px 600px at 80% -10%, #fdf6e9 0%, ${parchment} 45%, #f3eee4 100%)`,
    fontFamily: "'Inter',-apple-system,system-ui,sans-serif", color: ink, padding: "26px 34px 70px", maxWidth: 1180, margin: "0 auto" },
  topbar: { display: "flex", alignItems: "center", justifyContent: "space-between", marginBottom: 30, gap: 16, flexWrap: "wrap" },
  brand: { display: "flex", alignItems: "center", gap: 12 },
  mark: { width: 42, height: 42, borderRadius: 13, display: "grid", placeItems: "center",
    background: `linear-gradient(135deg, ${ink}, #2d3a52)`, color: "#f0d9a8", fontFamily: "Georgia,serif",
    fontSize: 22, fontWeight: 700, boxShadow: "0 6px 18px rgba(28,36,51,0.22)" },
  brandName: { fontFamily: "Georgia,serif", fontSize: 19, fontWeight: 700, letterSpacing: "-0.01em" },
  brandSub: { fontSize: 12, color: brass, fontWeight: 600 },
  nav: { display: "flex", gap: 4, background: "rgba(28,36,51,0.04)", padding: 5, borderRadius: 13 },
  navItem: { border: "none", background: "transparent", padding: "8px 16px", borderRadius: 9, fontSize: 13.5,
    fontWeight: 500, color: "#5b6678", cursor: "pointer", fontFamily: "inherit", transition: "all .2s ease" },
  navItemActive: { background: "#fff", color: ink, boxShadow: "0 2px 8px rgba(28,36,51,0.08)", fontWeight: 600 },
  topRight: { display: "flex", alignItems: "center", gap: 12 },
  curSwitch: { display: "flex", gap: 3, background: "rgba(28,36,51,0.04)", padding: 4, borderRadius: 11 },
  curBtn: { border: "none", background: "transparent", padding: "7px 11px", borderRadius: 8, fontSize: 12.5,
    fontWeight: 600, color: "#5b6678", cursor: "pointer", fontFamily: "inherit", transition: "all .2s ease" },
  curBtnActive: { background: "#fff", color: ink, boxShadow: "0 2px 6px rgba(28,36,51,0.1)" },
  addCta: { border: "none", padding: "11px 18px", borderRadius: 12, cursor: "pointer",
    background: `linear-gradient(135deg, ${ink}, #313f59)`, color: "#fbf3e2", fontSize: 13.5, fontWeight: 600,
    fontFamily: "inherit", boxShadow: "0 6px 18px rgba(28,36,51,0.25)" },
  logout: { width: 38, height: 38, borderRadius: 11, border: "1px solid rgba(28,36,51,0.1)", background: "rgba(255,255,255,0.6)",
    color: "#5b6678", cursor: "pointer", fontSize: 15, fontFamily: "inherit" },

  hero: { position: "relative", overflow: "hidden", background: `linear-gradient(135deg, ${ink} 0%, #243149 55%, #2b3a55 100%)`,
    borderRadius: 24, padding: "34px 38px", marginBottom: 22, display: "flex", alignItems: "center",
    justifyContent: "space-between", gap: 30, boxShadow: "0 20px 50px rgba(28,36,51,0.28)", flexWrap: "wrap" },
  heroGlow: { position: "absolute", top: -120, right: -60, width: 360, height: 360, borderRadius: "50%",
    background: "radial-gradient(circle, rgba(212,175,106,0.30), transparent 65%)", pointerEvents: "none" },
  heroLeft: { position: "relative", zIndex: 1, minWidth: 280 },
  heroKicker: { fontSize: 11.5, letterSpacing: "0.2em", color: "#d4af6a", fontWeight: 700, marginBottom: 10 },
  heroBig: { fontFamily: "Georgia,serif", fontSize: 52, fontWeight: 700, color: "#fbf3e2", lineHeight: 1,
    letterSpacing: "-0.02em", fontVariantNumeric: "tabular-nums" },
  heroOf: { fontSize: 14, color: "rgba(251,243,226,0.6)", marginTop: 10 },
  goalControl: { marginTop: 22, maxWidth: 320 },
  goalControlTop: { display: "flex", alignItems: "center", justifyContent: "space-between", marginBottom: 10 },
  goalControlLabel: { fontSize: 11, letterSpacing: "0.1em", textTransform: "uppercase", color: "rgba(251,243,226,0.5)", fontWeight: 600 },
  goalInputWrap: { display: "flex", alignItems: "center", background: "rgba(255,255,255,0.1)", borderRadius: 9,
    padding: "4px 10px", border: "1px solid rgba(255,255,255,0.15)" },
  goalInputSym: { color: "#d4af6a", fontSize: 14, fontWeight: 700 },
  goalInput: { width: 64, border: "none", background: "transparent", color: "#fbf3e2", fontSize: 15, fontWeight: 700,
    fontFamily: "inherit", outline: "none", textAlign: "right", fontVariantNumeric: "tabular-nums" },
  range: { width: "100%" },
  rangeTicks: { display: "flex", justifyContent: "space-between", fontSize: 10.5, color: "rgba(251,243,226,0.4)", marginTop: 6 },
  ring: { position: "relative", zIndex: 1, display: "grid", placeItems: "center" },
  ringCenter: { position: "absolute", textAlign: "center" },
  ringPct: { fontFamily: "Georgia,serif", fontSize: 34, fontWeight: 700, color: "#fbf3e2" },
  ringPctSm: { fontFamily: "Georgia,serif", fontSize: 22, fontWeight: 700, color: "#fbf3e2" },
  ringLabel: { fontSize: 10.5, letterSpacing: "0.1em", textTransform: "uppercase", color: "rgba(251,243,226,0.55)", marginTop: 3 },

  grid: { display: "grid", gridTemplateColumns: "1fr 1.15fr", gap: 22 },
  card: { background: "rgba(255,255,255,0.72)", backdropFilter: "blur(10px)", border: "1px solid rgba(28,36,51,0.06)",
    borderRadius: 22, padding: "24px 26px", boxShadow: "0 10px 30px rgba(28,36,51,0.06)" },
  cardHead: { display: "flex", alignItems: "flex-start", justifyContent: "space-between", marginBottom: 20, gap: 12, flexWrap: "wrap" },
  cardTitle: { margin: 0, fontFamily: "Georgia,serif", fontSize: 19, fontWeight: 700, letterSpacing: "-0.01em" },
  cardHint: { fontSize: 11.5, color: "#9aa3b2", display: "block", marginTop: 4 },
  linkBtn: { border: "none", background: "transparent", color: brass, fontSize: 12.5, fontWeight: 600, cursor: "pointer", fontFamily: "inherit" },

  calHeader: { display: "flex", alignItems: "center", justifyContent: "space-between", marginBottom: 18, gap: 12 },
  calHeaderCenter: { textAlign: "center", flex: 1 },
  calMonthTitle: { margin: 0, fontFamily: "Georgia,serif", fontSize: 24, fontWeight: 700, letterSpacing: "-0.01em" },
  calYear: { color: brass, fontWeight: 700 },
  calArrow: { width: 44, height: 44, borderRadius: 12, border: "1px solid rgba(28,36,51,0.1)", background: "rgba(255,255,255,0.6)",
    fontSize: 24, color: ink, cursor: "pointer", lineHeight: 1, fontFamily: "Georgia,serif", flexShrink: 0 },
  dowRow: { display: "grid", gridTemplateColumns: "repeat(7,1fr)", gap: 6, marginBottom: 8 },
  dowCell: { textAlign: "center", fontSize: 11, fontWeight: 600, color: "#9aa3b2", letterSpacing: "0.05em" },
  calGrid: { display: "grid", gridTemplateColumns: "repeat(7,1fr)", gap: 6 },
  calEmpty: { aspectRatio: "1 / 0.82" },
  calDay: { aspectRatio: "1 / 0.82", border: "1px solid rgba(28,36,51,0.06)", borderRadius: 11, background: "rgba(255,255,255,0.45)",
    padding: "7px 8px", cursor: "pointer", display: "flex", flexDirection: "column", alignItems: "stretch",
    fontFamily: "inherit", textAlign: "left", overflow: "hidden", position: "relative" },
  calDayTop: { display: "flex", alignItems: "center", justifyContent: "space-between" },
  calDayNum: { fontSize: 13, fontWeight: 600, color: "#3a4252" },
  calDayNumHol: { color: "#dc2626", fontWeight: 700 },
  holDot: { width: 6, height: 6, borderRadius: "50%", background: "#dc2626" },
  holName: { fontSize: 8.5, color: "#dc2626", fontWeight: 600, lineHeight: 1.1, marginTop: 2, overflow: "hidden",
    textOverflow: "ellipsis", whiteSpace: "nowrap" },
  calFlows: { marginTop: "auto", display: "flex", flexDirection: "column", gap: 1 },
  flowIn: { fontSize: 9.5, fontWeight: 700, color: "#5c7a3c", fontVariantNumeric: "tabular-nums" },
  flowOut: { fontSize: 9.5, fontWeight: 700, color: "#9a6b34", fontVariantNumeric: "tabular-nums" },

  catList: { display: "flex", flexDirection: "column", gap: 17 },
  catRow: { cursor: "pointer" },
  catTop: { display: "flex", alignItems: "center", gap: 9, marginBottom: 9 },
  catDot: { width: 9, height: 9, borderRadius: "50%", flexShrink: 0 },
  catName: { fontSize: 14, fontWeight: 600, flex: 1 },
  catSpent: { fontSize: 14, fontWeight: 700, fontVariantNumeric: "tabular-nums" },
  catOf: { color: "#c2cad6", fontSize: 13 },
  limitInput: { width: 56, border: "1px solid rgba(28,36,51,0.1)", borderRadius: 7, padding: "3px 7px", fontSize: 13,
    fontFamily: "inherit", color: "#5b6678", textAlign: "right", fontVariantNumeric: "tabular-nums", background: "rgba(255,255,255,0.6)" },
  track: { height: 8, borderRadius: 99, background: "rgba(28,36,51,0.07)", overflow: "hidden" },
  fill: { height: "100%", borderRadius: 99, transition: "width 1s cubic-bezier(.16,1,.3,1)" },
  overTag: { fontSize: 11, color: "#9a3412", fontWeight: 600, marginTop: 6 },

  filterPills: { display: "flex", gap: 6, flexWrap: "wrap", maxWidth: 340 },
  pill: { border: "1px solid rgba(28,36,51,0.08)", background: "rgba(255,255,255,0.5)", borderRadius: 99, padding: "5px 12px",
    fontSize: 12, fontWeight: 500, color: "#5b6678", cursor: "pointer", fontFamily: "inherit", transition: "all .2s ease" },
  pillActive: { background: ink, color: "#fbf3e2", borderColor: ink },
  entryList: { display: "flex", flexDirection: "column" },
  entry: { display: "flex", alignItems: "center", gap: 12, padding: "12px 10px", borderRadius: 12 },
  entryMain: { flex: 1, minWidth: 0 },
  entryDesc: { fontSize: 14, fontWeight: 600, whiteSpace: "nowrap", overflow: "hidden", textOverflow: "ellipsis" },
  entryMeta: { fontSize: 12, color: "#8a93a3", marginTop: 2, display: "flex", alignItems: "center", gap: 8 },
  recurBadge: { fontSize: 10.5, fontWeight: 600, color: brass, background: "rgba(184,134,59,0.1)", padding: "2px 7px", borderRadius: 99 },
  entryAmt: { fontSize: 14.5, fontWeight: 700, fontVariantNumeric: "tabular-nums" },
  del: { border: "none", background: "transparent", color: "#c2cad6", cursor: "pointer", fontSize: 13, padding: 4 },
  empty: { textAlign: "center", color: "#9aa3b2", fontSize: 13.5, padding: "30px 0" },

  scopeToggle: { display: "flex", gap: 3, background: "rgba(28,36,51,0.05)", padding: 4, borderRadius: 10 },
  scopeBtn: { border: "none", background: "transparent", padding: "6px 14px", borderRadius: 7, fontSize: 12.5,
    fontWeight: 600, color: "#5b6678", cursor: "pointer", fontFamily: "inherit", transition: "all .2s ease" },
  scopeBtnOn: { background: "#fff", color: ink, boxShadow: "0 2px 6px rgba(28,36,51,0.1)" },

  catChartArea: { position: "relative", paddingLeft: 8 },
  gridLine: { position: "absolute", left: 0, right: 0, borderTop: "1px solid rgba(28,36,51,0.06)" },
  gridLabel: { position: "absolute", left: 0, top: -8, fontSize: 10, color: "#b3bac6" },
  catGroups: { position: "absolute", left: 44, right: 8, bottom: 0, top: 0, display: "flex", alignItems: "flex-end",
    justifyContent: "space-around", gap: 10 },
  catGroup: { display: "flex", flexDirection: "column", alignItems: "center", flex: 1, height: "100%", justifyContent: "flex-end" },
  catGroupBars: { display: "flex", alignItems: "flex-end", gap: 3, height: "100%", width: "100%", justifyContent: "center" },
  catBar: { width: "13%", maxWidth: 22, minWidth: 6, borderRadius: "4px 4px 0 0", minHeight: 3,
    animation: "growUp .8s cubic-bezier(.16,1,.3,1) forwards", transformOrigin: "bottom" },
  catGroupLabel: { fontSize: 11.5, color: "#8a93a3", marginTop: 8, fontWeight: 500 },
  catChartLegend: { display: "flex", flexWrap: "wrap", gap: 14, justifyContent: "center", marginTop: 18,
    paddingTop: 16, borderTop: "1px solid rgba(28,36,51,0.06)" },
  legendRow: { display: "flex", gap: 18, marginTop: 14, justifyContent: "center" },
  legendItem: { display: "flex", alignItems: "center", gap: 6, fontSize: 12, color: "#5b6678", fontWeight: 500 },
  legendDot: { width: 9, height: 9, borderRadius: "50%" },

  acctList: { display: "flex", flexDirection: "column" },
  acctRow: { display: "flex", alignItems: "center", gap: 14, padding: "13px 10px", borderRadius: 12 },
  acctMain: { flex: 1, minWidth: 0 },
  acctName: { fontSize: 14, fontWeight: 600, display: "flex", alignItems: "center", gap: 8, marginBottom: 7 },
  marketBadge: { fontSize: 9.5, fontWeight: 700, color: brass, background: "rgba(184,134,59,0.12)", padding: "2px 7px",
    borderRadius: 99, letterSpacing: "0.03em", textTransform: "uppercase" },
  acctBar: { height: 6, borderRadius: 99, background: "rgba(28,36,51,0.07)", overflow: "hidden" },
  acctBarFill: { height: "100%", borderRadius: 99, background: `linear-gradient(90deg, ${brass}, #d4af6a)`,
    transition: "width .8s cubic-bezier(.16,1,.3,1)" },
  acctInputWrap: { display: "flex", alignItems: "center", background: "rgba(255,255,255,0.7)", border: "1px solid rgba(28,36,51,0.1)",
    borderRadius: 9, padding: "6px 10px" },
  acctSym: { color: "#9aa3b2", fontSize: 13, fontWeight: 600 },
  acctInput: { width: 80, border: "none", background: "transparent", fontSize: 14, fontWeight: 700, color: ink,
    fontFamily: "inherit", outline: "none", textAlign: "right", fontVariantNumeric: "tabular-nums" },
  acctVal: { fontSize: 12.5, fontWeight: 700, color: "#5c7a3c", width: 64, textAlign: "right", fontVariantNumeric: "tabular-nums" },

  overlay: { position: "fixed", inset: 0, background: "rgba(28,36,51,0.45)", backdropFilter: "blur(4px)",
    display: "grid", placeItems: "center", zIndex: 50, animation: "fadeIn .25s ease", padding: 20 },
  modal: { position: "relative", overflow: "hidden", width: "min(520px,94vw)", maxHeight: "92vh", overflowY: "auto",
    background: parchment, borderRadius: 24, padding: "30px 32px", boxShadow: "0 30px 80px rgba(0,0,0,0.4)",
    animation: "popIn .35s cubic-bezier(.16,1,.3,1)" },
  modalGlow: { position: "absolute", top: -100, right: -60, width: 280, height: 280, borderRadius: "50%",
    background: "radial-gradient(circle, rgba(212,175,106,0.18), transparent 65%)", pointerEvents: "none" },
  modalKicker: { fontSize: 11, letterSpacing: "0.2em", color: brass, fontWeight: 700, marginBottom: 6 },
  modalTitle: { margin: "0 0 22px", fontFamily: "Georgia,serif", fontSize: 24, fontWeight: 700, letterSpacing: "-0.01em" },
  modalError: { background: "rgba(154,52,18,0.08)", color: "#9a3412", fontSize: 13, padding: "9px 12px", borderRadius: 9, marginTop: 4 },
  typeToggle: { display: "flex", gap: 8, marginBottom: 18, background: "rgba(28,36,51,0.05)", padding: 5, borderRadius: 12 },
  typeBtn: { flex: 1, border: "none", background: "transparent", padding: "10px", borderRadius: 9, fontSize: 13.5,
    fontWeight: 600, color: "#5b6678", cursor: "pointer", fontFamily: "inherit", transition: "all .2s ease" },
  typeBtnOut: { background: "#fff", color: "#9a6b34", boxShadow: "0 2px 8px rgba(28,36,51,0.08)" },
  typeBtnIn: { background: "#fff", color: "#5c7a3c", boxShadow: "0 2px 8px rgba(28,36,51,0.08)" },
  field: { display: "block", marginBottom: 16 },
  fieldRow: { display: "flex", gap: 12 },
  fieldLabel: { fontSize: 12, fontWeight: 600, color: "#6b7585" },
  fieldLabelRow: { display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 7 },
  miniLink: { border: "none", background: "transparent", color: brass, fontSize: 11.5, fontWeight: 600, cursor: "pointer", fontFamily: "inherit" },
  input: { width: "100%", border: "1px solid rgba(28,36,51,0.12)", borderRadius: 11, padding: "11px 13px", fontSize: 14,
    fontFamily: "inherit", color: ink, background: "rgba(255,255,255,0.8)", outline: "none", marginTop: 7 },
  catPicker: { display: "flex", flexWrap: "wrap", gap: 7, marginTop: 7 },
  catPick: { display: "flex", alignItems: "center", gap: 7, border: "1px solid rgba(28,36,51,0.1)", background: "rgba(255,255,255,0.6)",
    borderRadius: 99, padding: "7px 13px", fontSize: 13, fontWeight: 500, color: "#5b6678", cursor: "pointer",
    fontFamily: "inherit", transition: "all .2s ease" },
  catPickActive: { borderColor: brass, background: "rgba(184,134,59,0.1)", color: ink, fontWeight: 600 },
  recurPicker: { display: "flex", flexWrap: "wrap", gap: 7, marginTop: 7 },
  recurPick: { border: "1px solid rgba(28,36,51,0.1)", background: "rgba(255,255,255,0.6)", borderRadius: 10, padding: "7px 13px",
    fontSize: 13, fontWeight: 500, color: "#5b6678", cursor: "pointer", fontFamily: "inherit", transition: "all .2s ease" },
  recurPickActive: { borderColor: ink, background: ink, color: "#fbf3e2", fontWeight: 600 },
  recurNote: { fontSize: 12, color: brass, marginTop: 10, fontWeight: 500 },
  modalActions: { display: "flex", justifyContent: "flex-end", gap: 10, marginTop: 24 },
  ghostBtn: { border: "1px solid rgba(28,36,51,0.12)", background: "transparent", borderRadius: 11, padding: "11px 18px",
    fontSize: 13.5, fontWeight: 600, color: "#5b6678", cursor: "pointer", fontFamily: "inherit" },
  primaryBtn: { border: "none", borderRadius: 11, padding: "11px 22px", fontSize: 13.5, fontWeight: 600, color: "#fbf3e2",
    background: `linear-gradient(135deg, ${ink}, #313f59)`, fontFamily: "inherit", boxShadow: "0 6px 18px rgba(28,36,51,0.25)", cursor: "pointer" },
  catMgrList: { display: "flex", flexDirection: "column", gap: 8, marginBottom: 16 },
  catMgrRow: { display: "flex", alignItems: "center", gap: 10, padding: "8px 10px", borderRadius: 10, background: "rgba(255,255,255,0.5)" },
  catMgrName: { flex: 1, border: "1px solid transparent", borderRadius: 8, padding: "6px 8px", fontSize: 13.5, fontWeight: 600,
    fontFamily: "inherit", color: ink, background: "transparent", outline: "none" },
  catMgrAdd: { display: "flex", alignItems: "center", gap: 10, paddingTop: 16, borderTop: "1px solid rgba(28,36,51,0.08)" },
  checkRow: { display: "flex", alignItems: "center", gap: 10, fontSize: 13.5, color: "#5b6678", cursor: "pointer", marginBottom: 8 },
  checkbox: { width: 22, height: 22, borderRadius: 7, border: "1px solid rgba(28,36,51,0.2)", display: "grid", placeItems: "center",
    fontSize: 13, color: "#fbf3e2", background: "rgba(255,255,255,0.6)" },
  checkboxOn: { background: brass, borderColor: brass },
  placeholder: { textAlign: "center", padding: "90px 20px", background: "rgba(255,255,255,0.5)", borderRadius: 22, border: "1px dashed rgba(28,36,51,0.12)" },
  placeholderMark: { fontSize: 40, color: brass, marginBottom: 14 },
  placeholderTitle: { margin: 0, fontFamily: "Georgia,serif", fontSize: 24, fontWeight: 700 },
  placeholderText: { color: "#8a93a3", fontSize: 14, maxWidth: 460, margin: "10px auto 0", lineHeight: 1.6 },
};
